# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba512a1d078a1e6a805d3eead410891c5886af49f4ade57cb7ffdc563a8ee2b5420cbc0a7b5786b093d5d31a3fd6382eaeb27dc4569fb16a139afd7a5219d18a

test:
  secret_key_base: 7c70d4b0db6f30bf9bc78a5fbaa13e732653c5fabd13b2b65b590e16e67db9d9b879ab89a0fcae3324ba9270aa1990691c54943ba3abfad04274c148569b64c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
